### ISSUE TITLE
Multiple languages in single compact csv file using namespaces failed to build

### ISSUE THREAD

**Issue by lethefrost** [slang-i18n/slang#256]
It seems that if you enable `namespaces` to separate different kinds of texts, then using the compact csv (only one file for one namespace) will cause the error below when running `dart run slang` 

```
Generating translations...

Found slang.yaml!

 -> fileType: csv
 -> baseLocale: en
 -> fallbackStrategy: baseLocale
 -> inputDirectory: assets/i18n
 -> inputFilePattern: .csv
 -> outputDirectory: lib/i18n
 -> outputFileName: strings.g.dart
 -> lazy: true
 -> localeHandling: true
 -> flutterIntegration: true
 -> namespaces: true
 -> translateVar: t
 -> enumName: AppLocale
 -> translationClassVisibility: private
 -> keyCase: null (no change)
 -> keyCase (for maps): null (no change)
 -> paramCase: null (no change)
 -> stringInterpolation: dart
 -> renderFlatMap: true
 -> translationOverrides: false
 -> renderTimestamp: true
 -> renderStatistics: true
 -> maps: []
 -> pluralization/auto: cardinal
 -> pluralization/default_parameter: n
 -> pluralization/cardinal: []
 -> pluralization/ordinal: []
 -> contexts: no custom contexts
 -> interfaces: no interfaces
 -> obfuscation: disabled
 -> format: disabled
 -> imports: []

Unhandled exception:
Null check operator used on a null value
#0      SlangFileCollectionBuilder.fromFileModel.<anonymous closure> (package:slang/src/builder/builder/slang_file_collection_builder.dart:124:49)
#1      MappedIterator.moveNext (dart:_internal/iterable.dart:403:20)
#2      IterableNullableExtension.whereNotNull (package:collection/src/iterable_extensions.dart:605:25)
#3      _SyncStarIterator.moveNext (dart:async-patch/async_patch.dart:560:14)
#4      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#5      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#6      new List.of (dart:core-patch/array_patch.dart:39:18)
#7      IterableExtension.sortedBy (package:collection/src/iterable_extensions.dart:66:20)
#8      SlangFileCollectionBuilder.fromFileModel (package:slang/src/builder/builder/slang_file_collection_builder.dart:146:12)
#9      SlangFileCollectionBuilder.readFromFileSystem (package:slang/src/builder/builder/slang_file_collection_builder.dart:59:12)
#10     main (file:///Users/lethe/.pub-cache/hosted/pub.dev/slang-4.1.0/bin/slang.dart:124:34)
#11     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#12     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```
 and the error `#0` points to the following piece of code:

```dart
              // secondary files (strings_x)
              final match = RegexUtils.fileWithLocaleRegex
                  .firstMatch(fileNameNoExtension);
              if (match != null) {
                final namespace = match.group(1)!;
                final locale = I18nLocale(
                  language: match.group(2)!,
                  script: match.group(3),
                  country: match.group(4),
                );
```

seems that it is always looking for file names with locale code, so that `match.group(1)!` doesn't return `null`. I hope we can add support to compact csv as well so they can be correctly identified.

**Comment by Tienisto** [comment]
Does it work if you add an arbitrary locale to the file name like your base locale? (example `strings_en.csv`)
